const data = {
  products: [
    {
      name: 'Wrapround Linen Dress',
      slug: 'Wrapround-Linen-Dress',
      category: 'Dress',
      Image: '/images/p1.jpg',
      price: 3500,
      countInStock: 0,
      Material: 'Linen',
      rating: 4.5,
      numReviews: 25,
      description: 'Good quality Linen Wrapround Dress',
    },
    {
      name: 'Sleevless Shift Dress',
      slug: 'Sleevless-Shift-Dress',
      category: 'Dress',
      Image: '/images/p2.jpg',
      price: 2500,
      countInStock: 20,
      Material: 'Linen',
      rating: 2.5,
      numReviews: 10,
      description: 'Good quality Linen Sleevless Shift Dress',
    },
    {
      name: 'BackButton Sleevless Top',
      slug: 'Back-Button-Sleevless-Top',
      category: 'Tops',
      Image: '/images/p3.jpg',
      price: 1700,
      countInStock: 20,
      Material: 'Linen',
      rating: 4.5,
      numReviews: 20,
      description: 'Good quality Linen Back Button Sleevless Top',
    },
    {
      name: 'Sleeveless FrontButton Dress',
      slug: 'Sleeveless-Front-Button-Dress',
      category: 'Dress',
      Image: '/images/p4.jpg',
      price: 3500,
      countInStock: 20,
      Material: 'Linen',
      rating: 4.5,
      numReviews: 25,
      description: 'Good quality Linen Sleeveless Front Button Dress',
    },
    {
      name: 'Red Color Bottom Top',
      slug: 'Red-Color-Bottom-Top',
      category: 'Tops',
      Image: '/images/p5.jpg',
      price: 2800,
      countInStock: 20,
      Material: 'Linen',
      rating: 4.5,
      numReviews: 30,
      description: 'Good quality Linen Sleeveless Bottom Top',
    },
    {
      name: 'Yellow Color Top',
      slug: 'Yellow-Color-Top',
      category: 'Tops',
      Image: '/images/p6.jpg',
      price: 4500,
      countInStock: 20,
      Material: 'Linen',
      rating: 4.5,
      numReviews: 25,
      description: 'Good quality Tops',
    },
    {
      name: 'Red Short Skirt',
      slug: 'Red-Short-Skirt',
      category: 'Skirts',
      Image: '/images/p7.jpg',
      price: 2500,
      countInStock: 20,
      Material: 'Linen',
      rating: 4.5,
      numReviews: 25,
      description: 'Good quality Linen Skirts',
    },
    {
      name: 'Sleevless Black Top',
      slug: 'Sleevless-Black-Top',
      category: 'Top',
      Image: '/images/p8.jpg',
      price: 4500,
      countInStock: 20,
      Material: 'Linen',
      rating: 3.5,
      numReviews: 35,
      description: 'Good quality Linen Top',
    },
  ],
};

export default data;
